config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  devise_for :users
  root to: 'items#index'
  resources :users, only: [:show, :edit, :update]
  resources :cards, only: [:new, :create, :show, :destroy]
  resources :items do
    resources :comments, only: :create
    resources :managements, only: [:index, :create, :new] do
      collection do
        post 'registered'
      end
    end
    collection do
      get 'search'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: 'は半角英数字を含めてください' }

  with_options presence: true do
    validates :nickname
    validates :birth
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は全角で入力してください' }
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は全角で入力してください' }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'は全角カナで入力してください' }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'は全角カナで入力してください' }
  end

  has_many :items
  has_many :managements
  has_many :comments
  has_one :card, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def edit
  end

  def update
    current_user.update(user_params)

    if current_user.valid?
      sign_in(current_user, bypass: true)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :nickname, :email, :first_name, :last_name, :first_name_kana, :last_name_kana, :birth)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/second-header"%>


<%= form_with model: current_user, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報編集
    </h1>
  </div>
  
  <%= render "shared/error_messages", model: f.object%>
 
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) furima太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 山田" %>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :first_name_kana, class:"input-name", id:"first-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :last_name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birth,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>
<p class='identification'>パスワード変更</p>
   <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">新しいパスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">新しいパスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <div class="form-group">
  </div>

  <div class='register-btn'>
    <%= f.submit "変更" ,class:"register-red-btn" %>
  </div>
  <p class='register-info'>本人情報の登録について</p>
</div>
<% end %>

<%= render "shared/second-footer"%>

app/views/users/show.html.erb
<%= render "shared/second-header"%>

<div class= 'registration-main'>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報
    </h1>
  </div>

    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
    </div>
    <%= current_user.nickname %>
  </div>
   <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
    </div>
    <%= current_user.email %>
  </div>
 <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前（全角）</label>
    </div>
    <%= current_user.first_name %> <%= current_user.last_name %>
  </div>
 <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ（全角）</label>
    </div>
    <%= current_user.first_name_kana %> <%= current_user.last_name_kana %>
  </div>
 <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
    </div>
    <%= current_user.birth %>
  </div>

 <div class="edit-menu">
  <div class="menu"><%= link_to '■会員情報編集', edit_user_path(current_user), method: :get %></div>
  <div class="menu"><%= link_to '■カード情報登録', new_card_path %></div>
  <div class="menu"><%= link_to '■カード情報編集', card_path(current_user) %></div>
</div>

</div>
</div>

<%= render "shared/second-footer"%>