config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  devise_for :users
  root to: 'items#index'
  resources :users, only: [:show, :edit, :update]
  resources :cards, only: [:new, :create, :show, :destroy]
  resources :items do
    resources :comments, only: :create
    resources :managements, only: [:index, :create, :new] do
      collection do
        post 'registered'
      end
    end
    collection do
      get 'search'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  def new
    card = Card.new
  end

  def create
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    customer = Payjp::Customer.create(
      description: 'test',
      card: params[:token]
    )

    card = Card.new(
      card_token: params[:token],
      customer_token: customer.id,
      user_id: current_user.id
    )

    if card.save
      redirect_to root_path
    else
      redirect_to 'new'
    end
  end

  def show
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    card = Card.find_by(user_id: current_user.id)

    redirect_to new_card_path and return unless card.present?

    customer = Payjp::Customer.retrieve(card.customer_token)
    @card = customer.cards.first
  end

  def destroy
    card = Card.find_by(user_id: current_user.id)
    if card.destroy
      redirect_to root_path
    else
      render 'show'
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
 <div class='transaction-main'>
<%= form_with url: cards_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>

 <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :number, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_area :exp_month, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
          <p>月</p>
          <%= f.text_area :exp_year, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
          <p>年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :cvc,class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
      </div>
    </div>
      <div class='buy-btn'>
      <%= f.submit "登録" ,class:"buy-red-btn" %>
    </div>
    <% end %>
   </div>
  </div>
 </div>
</div>
<%= render "shared/second-footer"%>

app/views/cards/show.html.erb
<%= render "shared/second-header"%>

<div class= 'registration-main'>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      カード情報
    </h1>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">カード番号</label>
    </div>
    <%= "**** **** ****" + @card[:last4] %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">有効期限</label>
    </div>
    <%= @card[:exp_year]%><%= "年" %><%= @card[:exp_month]%><%= "月" %>
  </div>
  <div class="edit-menu">
  <div class="card-destroy"><%= link_to '!!カード情報を削除する!!', card_path(current_user), method: :delete %></div>
  </div>
</div>
</div>

<%= render "shared/second-footer"%>